# Generated by Django 2.1.7 on 2019-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheredoyoulive', '0003_auto_20190404_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='coordinate_lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='coordinate_long',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
